#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Panoptic;
    
    #line 1 "..\..\Areas\Ops\Views\Status\Index.cshtml"
    using Panoptic.Plugins.UI.Ops.Areas.Ops.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Ops/Views/Status/Index.cshtml")]
    public partial class _Areas_Ops_Views_Status_Index_cshtml : System.Web.Mvc.WebViewPage<Panoptic.Plugins.UI.Ops.Areas.Ops.Models.EnvironmentStatusModel>
    {
        
        #line 8 "..\..\Areas\Ops\Views\Status\Index.cshtml"
            
    internal string StatusToText(ServiceStatus status)
    {
        switch (status)
        {
            case ServiceStatus.Ok:
                return "Ok";
            case ServiceStatus.Warning:
                return "Warning";
            case ServiceStatus.Error:
                return "Error";
            default:
                return "alert-info";
        }
    }

    internal string StatusToCssAlertClass(ServiceStatus status)
    {
        switch (status)
        {
            case ServiceStatus.Ok:
                return "alert-success";
            case ServiceStatus.Warning:
                return "alert-warning";
            case ServiceStatus.Error:
                return "alert-danger";
            default:
                return "Unknown";
        }
    }

        #line default
        #line hidden
        
        public _Areas_Ops_Views_Status_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Areas\Ops\Views\Status\Index.cshtml"
  
    ViewBag.Title = Model.Name;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

WriteLiteral("\r\n<div");

WriteLiteral(" class=\"jumbotron\"");

WriteLiteral(">\r\n    <h1>");

            
            #line 41 "..\..\Areas\Ops\Views\Status\Index.cshtml"
   Write(Html.DisplayFor(model => model.Name));

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n    <p");

WriteLiteral(" class=\"lead\"");

WriteLiteral(">");

            
            #line 42 "..\..\Areas\Ops\Views\Status\Index.cshtml"
               Write(Html.DisplayFor(model => model.Description));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n</div>\r\n<div>\r\n    <div>\r\n        <h2>Services</h2>\r\n        <p>\r\n         " +
"   The status of the different services.\r\n        </p>\r\n\r\n        <table");

WriteLiteral(" class=\"table table-striped\"");

WriteLiteral(">\r\n            <thead>\r\n                <tr>\r\n                    <th>Name</th>\r\n" +
"                    <th>Status</th>\r\n                    <th>Issues</th>\r\n      " +
"          </tr>\r\n            </thead>\r\n            <tbody>\r\n");

            
            #line 60 "..\..\Areas\Ops\Views\Status\Index.cshtml"
                
            
            #line default
            #line hidden
            
            #line 60 "..\..\Areas\Ops\Views\Status\Index.cshtml"
                 foreach (var service in Model.Services)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <tr>\r\n                        <td>");

            
            #line 63 "..\..\Areas\Ops\Views\Status\Index.cshtml"
                       Write(Html.DisplayFor(model => service.Name));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        <td");

WriteAttribute("class", Tuple.Create(" class=\"", 1745), Tuple.Create("\"", 1797)
, Tuple.Create(Tuple.Create("", 1753), Tuple.Create("alert", 1753), true)
            
            #line 64 "..\..\Areas\Ops\Views\Status\Index.cshtml"
, Tuple.Create(Tuple.Create(" ", 1758), Tuple.Create<System.Object, System.Int32>(StatusToCssAlertClass(service.Status)
            
            #line default
            #line hidden
, 1759), false)
);

WriteLiteral(">");

            
            #line 64 "..\..\Areas\Ops\Views\Status\Index.cshtml"
                                                                            Write(StatusToText(service.Status));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        <td>");

            
            #line 65 "..\..\Areas\Ops\Views\Status\Index.cshtml"
                       Write(Html.DisplayFor(model => service.Notification));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    </tr>\r\n");

            
            #line 67 "..\..\Areas\Ops\Views\Status\Index.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </tbody>\r\n        </table>\r\n        <br />\r\n\r\n        <h2>Machines</h" +
"2>\r\n        <p>\r\n            The status of the different machines.\r\n        </p>" +
"\r\n\r\n        <table");

WriteLiteral(" class=\"table table-striped\"");

WriteLiteral(">\r\n            <thead>\r\n                <tr>\r\n                    <th>Name</th>\r\n" +
"                    <th>Status</th>\r\n                    <th");

WriteLiteral(" colspan=\"2\"");

WriteLiteral(">CPU</th>\r\n                    <th");

WriteLiteral(" colspan=\"3\"");

WriteLiteral(@">Memory</th>
                    <th>Disks</th>
                    <th>Issues</th>
                </tr>
                <tr>
                    <th></th>
                    <th></th>
                    <th>Current</th>
                    <th>History</th>
                    <th>In use</th>
                    <th>Total</th>
                    <th>&#37; in use</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
");

            
            #line 100 "..\..\Areas\Ops\Views\Status\Index.cshtml"
                
            
            #line default
            #line hidden
            
            #line 100 "..\..\Areas\Ops\Views\Status\Index.cshtml"
                 foreach (var machine in Model.Machines)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <tr>\r\n                        <td>");

            
            #line 103 "..\..\Areas\Ops\Views\Status\Index.cshtml"
                       Write(Html.ActionLink(machine.Name, "Index", "MachineStatus", new { area = "ops", machine = machine.Name }, new { }));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        <td");

WriteAttribute("class", Tuple.Create(" class=\"", 3159), Tuple.Create("\"", 3211)
, Tuple.Create(Tuple.Create("", 3167), Tuple.Create("alert", 3167), true)
            
            #line 104 "..\..\Areas\Ops\Views\Status\Index.cshtml"
, Tuple.Create(Tuple.Create(" ", 3172), Tuple.Create<System.Object, System.Int32>(StatusToCssAlertClass(machine.Status)
            
            #line default
            #line hidden
, 3173), false)
);

WriteLiteral(">");

            
            #line 104 "..\..\Areas\Ops\Views\Status\Index.cshtml"
                                                                            Write(StatusToText(machine.Status));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        <td>");

            
            #line 105 "..\..\Areas\Ops\Views\Status\Index.cshtml"
                       Write(Html.DisplayFor(model => machine.CpuPercentage));

            
            #line default
            #line hidden
WriteLiteral(" &#37;</td>\r\n                        <td>CPU history ...</td>\r\n                  " +
"      <td>");

            
            #line 107 "..\..\Areas\Ops\Views\Status\Index.cshtml"
                       Write(Html.DisplayFor(model => machine.MemoryInUseInGb));

            
            #line default
            #line hidden
WriteLiteral(" Gb</td>\r\n                        <td>");

            
            #line 108 "..\..\Areas\Ops\Views\Status\Index.cshtml"
                       Write(Html.DisplayFor(model => machine.MemoryTotalInGb));

            
            #line default
            #line hidden
WriteLiteral(" Gb</td>\r\n                        <td>");

            
            #line 109 "..\..\Areas\Ops\Views\Status\Index.cshtml"
                       Write(Html.DisplayFor(model => machine.MemoryInUsePercentage));

            
            #line default
            #line hidden
WriteLiteral(" &#37;</td>\r\n                        <td>disks ....</td>\r\n                       " +
" <td>");

            
            #line 111 "..\..\Areas\Ops\Views\Status\Index.cshtml"
                       Write(Html.DisplayFor(model => machine.Notification));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    </tr>\r\n");

            
            #line 113 "..\..\Areas\Ops\Views\Status\Index.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </tbody>\r\n        </table>\r\n        <br />\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
