#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Panoptic;
    
    #line 1 "..\..\Areas\Ops\Views\MachineStatus\Index.cshtml"
    using Panoptic.Plugins.UI.Ops.Areas.Ops.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Ops/Views/MachineStatus/Index.cshtml")]
    public partial class _Areas_Ops_Views_MachineStatus_Index_cshtml : System.Web.Mvc.WebViewPage<Panoptic.Plugins.UI.Ops.Areas.Ops.Models.MachineStatusModel>
    {
        
        #line 8 "..\..\Areas\Ops\Views\MachineStatus\Index.cshtml"
            
    internal string StatusToText(ServiceStatus status)
    {
        switch (status)
        {
            case ServiceStatus.Ok:
                return "Ok";
            case ServiceStatus.Warning:
                return "Warning";
            case ServiceStatus.Error:
                return "Error";
            default:
                return "alert-info";
        }
    }

    internal string StatusToCssAlertClass(ServiceStatus status)
    {
        switch (status)
        {
            case ServiceStatus.Ok:
                return "alert-success";
            case ServiceStatus.Warning:
                return "alert-warning";
            case ServiceStatus.Error:
                return "alert-danger";
            default:
                return "Unknown";
        }
    }

        #line default
        #line hidden
        
        public _Areas_Ops_Views_MachineStatus_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Areas\Ops\Views\MachineStatus\Index.cshtml"
  
    ViewBag.Title = Model.Name;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

WriteLiteral("\r\n<div");

WriteLiteral(" class=\"jumbotron\"");

WriteLiteral(">\r\n    <h1>");

            
            #line 41 "..\..\Areas\Ops\Views\MachineStatus\Index.cshtml"
   Write(Html.DisplayFor(model => model.Name));

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n    <p");

WriteLiteral(" class=\"lead\"");

WriteLiteral(">");

            
            #line 42 "..\..\Areas\Ops\Views\MachineStatus\Index.cshtml"
               Write(Html.DisplayFor(model => model.Description));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n</div>\r\n<div>\r\n    <div>\r\n        <h2>Current status</h2>\r\n        <p>\r\n   " +
"         The current status of the machines.\r\n        </p>\r\n        <table");

WriteLiteral(" class=\"table table-striped\"");

WriteLiteral(">\r\n            <thead>\r\n                <tr>\r\n                    <th>Name</th>\r\n" +
"                    <th>Status</th>\r\n                    <th");

WriteLiteral(" colspan=\"2\"");

WriteLiteral(">CPU</th>\r\n                    <th");

WriteLiteral(" colspan=\"3\"");

WriteLiteral(@">Memory</th>
                    <th>Disks</th>
                    <th>Issues</th>
                </tr>
                <tr>
                    <th></th>
                    <th></th>
                    <th>Current</th>
                    <th>History</th>
                    <th>In use</th>
                    <th>Total</th>
                    <th>&#37; in use</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>");

            
            #line 74 "..\..\Areas\Ops\Views\MachineStatus\Index.cshtml"
                   Write(Html.DisplayFor(model => Model.Name));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td");

WriteAttribute("class", Tuple.Create(" class=\"", 2144), Tuple.Create("\"", 2194)
, Tuple.Create(Tuple.Create("", 2152), Tuple.Create("alert", 2152), true)
            
            #line 75 "..\..\Areas\Ops\Views\MachineStatus\Index.cshtml"
, Tuple.Create(Tuple.Create(" ", 2157), Tuple.Create<System.Object, System.Int32>(StatusToCssAlertClass(Model.Status)
            
            #line default
            #line hidden
, 2158), false)
);

WriteLiteral(">");

            
            #line 75 "..\..\Areas\Ops\Views\MachineStatus\Index.cshtml"
                                                                      Write(StatusToText(Model.Status));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 76 "..\..\Areas\Ops\Views\MachineStatus\Index.cshtml"
                   Write(Html.DisplayFor(model => Model.CpuPercentage));

            
            #line default
            #line hidden
WriteLiteral(" &#37;</td>\r\n                    <td>CPU history ...</td>\r\n                    <t" +
"d>");

            
            #line 78 "..\..\Areas\Ops\Views\MachineStatus\Index.cshtml"
                   Write(Html.DisplayFor(model => Model.MemoryInUseInGb));

            
            #line default
            #line hidden
WriteLiteral(" Gb</td>\r\n                    <td>");

            
            #line 79 "..\..\Areas\Ops\Views\MachineStatus\Index.cshtml"
                   Write(Html.DisplayFor(model => Model.MemoryTotalInGb));

            
            #line default
            #line hidden
WriteLiteral(" Gb</td>\r\n                    <td>");

            
            #line 80 "..\..\Areas\Ops\Views\MachineStatus\Index.cshtml"
                   Write(Html.DisplayFor(model => Model.MemoryInUsePercentage));

            
            #line default
            #line hidden
WriteLiteral(" &#37;</td>\r\n                    <td>disks ....</td>\r\n                    <td>");

            
            #line 82 "..\..\Areas\Ops\Views\MachineStatus\Index.cshtml"
                   Write(Html.DisplayFor(model => Model.Notification));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                </tr>\r\n            </tbody>\r\n        </table>\r\n\r\n        <" +
"h2>Logs</h2>\r\n        <p>\r\n            The latest logs coming from the machine.\r" +
"\n        </p>\r\n\r\n        <table");

WriteLiteral(" class=\"table table-striped\"");

WriteLiteral(">\r\n            <thead>\r\n                <tr>\r\n                    <th>Date</th>\r\n" +
"                    <th>Type</th>\r\n                    <th>Log</th>\r\n           " +
"     </tr>\r\n            </thead>\r\n            <tbody>\r\n");

            
            #line 101 "..\..\Areas\Ops\Views\MachineStatus\Index.cshtml"
                
            
            #line default
            #line hidden
            
            #line 101 "..\..\Areas\Ops\Views\MachineStatus\Index.cshtml"
                 foreach (var log in Model.Logs)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <tr>\r\n                        <td>");

            
            #line 104 "..\..\Areas\Ops\Views\MachineStatus\Index.cshtml"
                       Write(Html.DisplayFor(model => log.Date));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        <td>");

            
            #line 105 "..\..\Areas\Ops\Views\MachineStatus\Index.cshtml"
                       Write(Html.DisplayFor(model => log.Type));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        <td>");

            
            #line 106 "..\..\Areas\Ops\Views\MachineStatus\Index.cshtml"
                       Write(Html.DisplayFor(model => log.Text));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    </tr>\r\n");

            
            #line 108 "..\..\Areas\Ops\Views\MachineStatus\Index.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </tbody>\r\n        </table>\r\n    </div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
